### ISSUE TITLE
 KeyError: 'MQTT'

### ISSUE THREAD

**Issue by homdx** [penguineer/SmartBedroomPanel#3]
```
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Nov 23 2018, 12:11:28) 
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
[INFO   ] [Factory     ] 194 symbols loaded
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/configparser.py", line 1138, in _unify_values
     sectiondict = self._sections[section]
 KeyError: 'MQTT'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "SmartPanel.py", line 370, in <module>
     MQTT_HOST = config.get("MQTT", "host");
   File "/usr/lib64/python3.6/configparser.py", line 781, in get
     d = self._unify_values(section, vars)
   File "/usr/lib64/python3.6/configparser.py", line 1141, in _unify_values
     raise NoSectionError(section)
 configparser.NoSectionError: No section: 'MQTT'
```
```
pip list|grep mqtt
mqtt             0.0.1     
paho-mqtt        1.4.0     
```

**Comment by penguineer** [comment]
* [x]  Leave gracefully when config cannot be found
* [x]  Appropriate error messages on incomplete configuration
* [ ] Extend README.md on how to create a local copy
